<a href="https://colab.research.google.com/github/sagarkakkar03/Data-science/blob/main/1_Hypothesis_Testing_(Part2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('50_Startups.csv')

In [3]:
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [5]:
df.describe()

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [6]:
df.drop_duplicates()

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

## Test for feature elimination

In [4]:
from scipy.stats import shapiro
SL = 0.05
stat, p = shapiro(df['R&D Spend'])
if p < SL:
  print('Not normally distributed')
else:
  print('Normally distributed')

Normally distributed

In [5]:
stat, p = shapiro(df['Administration'])
if p < SL:
  print('Not normally distributed')
else:
  print('Normally distributed')

Normally distributed

In [7]:
from scipy.stats import ttest_ind

stat, p_value = ttest_ind(df['R&D Spend'], df['Administration'])
if p_value < SL:
  print('Features are the different')
else:
  print('Features are same')

Features are the different

In [8]:
from scipy.stats import wilcoxon
stat, p_value = wilcoxon(df['R&D Spend'], df['Administration'])
if p_value < SL:
  print('Features are the different')
else:
  print('Features are same')

Features are the different

## Chi square test

In [11]:
from scipy.stats import chi2_contingency
ct = pd.crosstab(df['Profit'], df['State'])
ct

State      California  Florida  New York
Profit
14681.40            1        0         0
35673.41            0        0         1
42559.73            1        0         0
49490.75            0        1         0
64926.08            0        0         1
65200.33            1        0         0
69758.98            0        0         1
71498.49            1        0         0
77798.83            0        1         0
78239.91            1        0         0
81005.76            1        0         0
81229.06            0        0         1
89949.14            1        0         0
90708.19            0        1         0
96479.51            0        0         1
96712.80            1        0         0
96778.92            0        1         0
97427.84            1        0         0
97483.56            0        0         1
99937.59            0        1         0
101004.64           0        0         1
103282.38           0        1         0
105008.31           0        0         1
105733.54           0        1         0
107404.34           1        0         0
108552.04           0        0         1
108733.99           0        1         0
110352.25           0        1         0
111313.02           0        0         1
118474.03           1        0         0
122776.86           0        0         1
124266.90           0        1         0
125370.37           0        0         1
126992.93           1        0         0
129917.04           0        0         1
132602.65           0        1         0
134307.35           1        0         0
141585.52           0        1         0
144259.40           1        0         0
146121.95           0        1         0
149759.96           1        0         0
152211.77           0        0         1
155752.60           0        1         0
156122.51           1        0         0
156991.12           0        0         1
166187.94           0        1         0
182901.99           0        0         1
191050.39           0        1         0
191792.06           1        0         0
192261.83           0        0         1

In [18]:
_, pvalue, _, _ = chi2_contingency(ct)
if pvalue < SL:
  print('Features are the same')
else:
  print('No similarity remove the state column')

Features are different