<a href="https://colab.research.google.com/github/sagarkakkar03/Data-science/blob/main/Data_Cleaning_Practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('inappropriate_data_assignment_dataset_50_records.csv')
df.head()

,Customer_ID,Age,Monthly_Income,Credit_Score,Gender,Education_Level,City,Loan_Status,City_dup
0,1008,83.0,78578.27,488.0,FEMALE,Gradute,PUNE,Pending,PUNE
1,1077,32.0,66351.58,840.0,Femlae,PG,Pune,rejected,Pune
2,1065,47.0,70782.39,571.0,FEMALE,Undergraduate,Delhi,approved,Delhi
3,1043,-5.0,77625.76,704.0,male,Under Graduate,Hyderabad,Pending,Hyderabad
4,1043,59.0,35856.88,547.0,M,post graduate,Chennai,Rejectd,Chennai

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      50 non-null     int64
 1   Age              50 non-null     float64
 2   Monthly_Income   50 non-null     float64
 3   Credit_Score     50 non-null     float64
 4   Gender           50 non-null     object
 5   Education_Level  50 non-null     object
 6   City             50 non-null     object
 7   Loan_Status      50 non-null     object
 8   City_dup         50 non-null     object
dtypes: float64(3), int64(1), object(5)
memory usage: 3.9+ KB

In [6]:
df.drop_duplicates(inplace=True, ignore_index=True)

In [16]:
df[df['Customer_ID'] <= 0]

Empty DataFrame
Columns: [Customer_ID, Age, Monthly_Income, Credit_Score, Gender, Education_Level, City, Loan_Status, City_dup]
Index: []

In [5]:
df[(df['Age'] <= 0) | (df['Age'] > 100)]

,Customer_ID,Age,Monthly_Income,Credit_Score,Gender,Education_Level,City,Loan_Status,City_dup
3,1043,-5.0,77625.76,704.0,male,Under Graduate,Hyderabad,Pending,Hyderabad
13,1076,102.0,58302.30,542.0,femAle,Post Graduate,Bengaluru,Approved,Bengaluru
17,1012,150.0,80866.94,312.0,male,UG,Bangalore,Approved,Bangalore

In [7]:
df['Age'].loc[(df['Age'] <= 0) | (df['Age'] > 100)] = np.nan

/tmp/ipython-input-3523558030.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Age'].loc[(df['Age'] <= 0) | (df['Age'] > 100)] = np.nan
/tmp/ipython-input-3523558030.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'].loc[(df['Age'] <= 0) | (df['Age'] > 100)] = np.nan

In [25]:
df[df['Monthly_Income'] < 0]

,Customer_ID,Age,Monthly_Income,Credit_Score,Gender,Education_Level,City,Loan_Status,City_dup
6,1008,64.0,-45000.0,746.0,M,Post Graduate,Mumbai,Rejectd,Mumbai

In [8]:
df['Monthly_Income'].loc[df['Monthly_Income'] < 0] = np.nan

/tmp/ipython-input-3820535400.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Monthly_Income'].loc[df['Monthly_Income'] < 0] = np.nan
/tmp/ipython-input-3820535400.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Monthly_Income'].loc[df['Monthly_Income'] < 0] = np.nan

In [9]:
df['Credit_Score'].loc[df['Credit_Score'] < 0] = np.nan

/tmp/ipython-input-496770723.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Credit_Score'].loc[df['Credit_Score'] < 0] = np.nan
/tmp/ipython-input-496770723.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Credit_Score'].loc[df['Credit_Score'] < 0] = np.nan

In [9]:
df['Gender'].unique()

array(['FEMALE', 'Femlae', 'male', 'M', 'Unknown', 'F', 'female',
       'femAle', 'Male', ' MALE '], dtype=object)

In [10]:
df['Gender'].replace(['FEMALE', 'Femlae', 'male', 'female',
       'femAle', 'Male', ' MALE '], ['F', 'F', 'M', 'F', 'F', 'M', 'M'], inplace=True)

/tmp/ipython-input-1602213196.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].replace(['FEMALE', 'Femlae', 'male', 'female',

In [11]:
df.head()

,Customer_ID,Age,Monthly_Income,Credit_Score,Gender,Education_Level,City,Loan_Status,City_dup
0,1008,83.0,78578.27,488.0,F,Gradute,PUNE,Pending,PUNE
1,1077,32.0,66351.58,840.0,F,PG,Pune,rejected,Pune
2,1065,47.0,70782.39,571.0,F,Undergraduate,Delhi,approved,Delhi
3,1043,NaN,77625.76,704.0,M,Under Graduate,Hyderabad,Pending,Hyderabad
4,1043,59.0,35856.88,547.0,M,post graduate,Chennai,Rejectd,Chennai

In [13]:
print(df['Education_Level'].unique())
print(df['City'].unique())
print(df['Loan_Status'].unique())

['Gradute' 'PG' 'Undergraduate' 'Under Graduate' 'post graduate'
 'Graduate' 'Post Graduate' 'PhD' 'UG']
['PUNE' 'Pune' 'Delhi' 'Hyderabad' 'Chennai' 'Mumbai' 'Bengaluru'
 ' Delhi ' 'Bangalore' 'mumbai ']
['Pending' 'rejected ' 'approved' 'Rejectd' 'Rejected' 'Approved'
 'APPROVED']

In [16]:
df[(df['City_dup'] != df['City'])]

Empty DataFrame
Columns: [Customer_ID, Age, Monthly_Income, Credit_Score, Gender, Education_Level, City, Loan_Status, City_dup]
Index: []

In [17]:
df.drop(columns = ['City_dup'], inplace=True)

In [21]:
df['Loan_Status'].replace('Rejectd', 'rejected', inplace=True)
df['Loan_Status'] = df['Loan_Status'].apply(str.lower)
df['City'].replace('Bengaluru', 'Bangalore', inplace=True)
df['City'] = df['City'].apply(str.lower)
df['Education_Level'] = df['Education_Level'].apply(str.lower)
df['Education_Level'].replace(['undergraduate', 'post graduate', 'gradute', 'under graduate'], ['ug', 'pg', 'graduate', 'ug'], inplace=True)

/tmp/ipython-input-3551022700.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Loan_Status'].replace('Rejectd', 'rejected', inplace=True)
/tmp/ipython-input-3551022700.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].replace('Bengaluru', 'Bangalore', inplace=True)
/tmp/ipython-input-3551022700.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Education_Level'].replace(['undergraduate', 'post graduate', 'gradute', 'under graduate'], ['ug', 'pg', 'graduate', 'ug'], inplace=True)

In [22]:
df

,Customer_ID,Age,Monthly_Income,Credit_Score,Gender,Education_Level,City,Loan_Status
0,1008,83.0,78578.27,488.0,F,graduate,pune,pending
1,1077,32.0,66351.58,840.0,F,pg,pune,rejected
2,1065,47.0,70782.39,571.0,F,ug,delhi,approved
3,1043,NaN,77625.76,704.0,M,ug,hyderabad,pending
4,1043,59.0,35856.88,547.0,M,pg,chennai,rejected
5,1085,18.0,58606.58,200.0,F,graduate,chennai,rejected
6,1008,64.0,NaN,746.0,M,pg,mumbai,rejected
7,1069,28.0,52222.44,879.0,F,pg,bangalore,rejected
8,1020,29.5,59497.15,421.0,F,pg,pune,pending
9,1009,76.0,94898.83,720.5,Unknown,ug,delhi,approved
10,1008,98.0,47683.38,419.0,F,phd,bangalore,rejected
11,1097,82.0,84365.57,715.0,F,ug,bangalore,rejected
12,1073,17.0,31342.60,762.0,F,graduate,delhi,rejected
13,1076,NaN,58302.30,542.0,F,pg,bangalore,approved
14,1071,51.0,125000.75,728.0,F,pg,mumbai,approved
15,1078,44.0,76724.45,426.0,Unknown,phd,pune,approved
16,1051,96.0,79224.53,301.0,F,ug,hyderabad,pending
17,1012,NaN,80866.94,312.0,M,ug,bangalore,approved
18,1083,21.0,58025.50,540.0,M,ug,pune,approved
19,1045,57.0,55752.96,900.0,Unknown,ug,delhi,rejected
20,1050,86.0,82159.52,332.0,F,pg,bangalore,pending
21,1037,32.0,61173.91,546.0,M,ug,mumbai,approved
22,1018,56.0,0.00,707.0,F,phd,hyderabad,rejected
23,1092,26.0,42334.26,381.0,F,ug,bangalore,approved
24,1078,76.0,46610.95,719.0,F,ug,bangalore,approved
25,1077,57.0,74943.21,448.0,F,pg,pune,rejected
26,1040,44.0,67848.51,775.0,F,pg,delhi,pending
27,1082,35.0,78809.71,626.0,F,ug,delhi,rejected
28,1054,65.0,56454.95,605.0,M,graduate,bangalore,approved
29,1044,75.0,68170.79,364.0,M,pg,delhi,rejected
30,1045,99.0,77511.81,551.0,F,pg,pune,approved
31,1022,45.2,58813.07,806.0,F,graduate,chennai,rejected
32,1009,29.0,74135.50,262.0,M,pg,chennai,rejected
33,1055,89.0,51761.48,743.0,F,pg,delhi,approved
34,1088,71.0,57738.92,570.0,F,pg,pune,rejected
35,1006,78.0,57365.24,717.0,F,pg,mumbai,approved
36,1085,23.0,41083.21,681.0,F,ug,pune,rejected
37,1082,43.0,74739.45,530.0,Unknown,pg,bangalore,pending
38,1027,84.0,55611.95,450.0,Unknown,graduate,bangalore,approved
39,1063,89.0,65249.88,657.0,F,ug,mumbai,approved
40,1016,54.0,74614.93,341.0,M,phd,delhi,pending
41,1075,87.0,73930.62,629.0,F,pg,mumbai,approved
42,1070,90.0,78307.70,311.0,F,phd,bangalore,approved
43,1035,49.0,63030.29,672.0,M,pg,pune,rejected
44,1006,95.0,56534.03,658.0,Unknown,ug,delhi,rejected
45,1097,40.0,63405.64,304.0,Unknown,pg,bangalore,approved
46,1044,36.0,31253.31,742.0,M,ug,pune,approved
47,1089,76.0,36057.75,520.0,F,ug,mumbai,pending
48,1067,72.0,38546.01,761.0,F,graduate,delhi,rejected
49,1077,27.0,45055.06,277.0,M,graduate,bangalore,approved